<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>Tweet_Audit</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="TweetAudit.Tests/**" />
		<Content Remove="TweetAudit.Tests/**" />
		<None Remove="TweetAudit.Tests/**" />
		<EmbeddedResource Remove="TweetAudit.Tests/**" />
	</ItemGroup>

	<ItemGroup>
		<None Include="Tweet Audit.sln" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="CsvHelper" Version="33.1.0" />
		<PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
		<PackageReference Include="Google.GenAI" Version="1.18.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
		<PackageReference Include="Moq" Version="4.20.72" />
	</ItemGroup>
	<ItemGroup>
		<None Update="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>